services:
  php:
    image: vendelev/cryptopro:5
    restart: unless-stopped
    build:
      context: .
      target: php
      dockerfile: docker/Dockerfile
      args:
        - LICENSE=${LICENSE}
    env_file:
      - path: .env
    volumes:
      - ./:/var/www
    ports:
      - "${HTTP_PORT}:80"
    logging:
      options:
        max-file: 1
        max-size: 5m
